[opener]
edit = [
	{ run = '${EDITOR:-nvim} "$@"', desc = "$EDITOR", block = true, for = "unix" },
]

# Speed up slow image previews
[tasks]
micro_workers    = 1
macro_workers    = 1
image_alloc      = 53687091
image_bound      = [ 0, 0 ]
